spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: root
    password: 1234567890Qq
  main:
    banner-mode: off


# 开启mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    banner: false
    #表前缀
    db-config:
      table-prefix: tbl_
      id-type: auto
server:
  port: 80

#jetcache:
#  #远程
#  remote:
#    default:
#      type: redis
#      host: localhost
#      port: 6379
#      poolConfig:
#        maxTotal: 50
#      keyConvertor: fastjson
#      valueDecode: java
#      valueEncode: java
#  #本地
#  local:
#    default:
#      type: linkedhashmap
#      keyConvertor: fastjson

jetcache:
  statIntervalMinutes: 1
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      host: localhost
      port: 6379
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        maxTotal: 50



