spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: root
    password: 1234567890Qq
  main:
    banner-mode: off

  cache:
    type: redis
    redis:

      cache-null-values: true

      #指定前缀
      key-prefix: aa

      #生命周期
      time-to-live: 10s


      enable-statistics: true

      #smsSpace
      use-key-prefix: true
  redis:
    port: 6379
    host: localhost


#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:ehcache.xml
# 开启mp的日志（输出到控制台）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    banner: false
    #表前缀
    db-config:
      table-prefix: tbl_
      id-type: auto
server:
  port: 80


memcached:
  # memcached服务器地址
  servers: localhost:11211
  # 连接池的数量
  poolSize: 10
  # 设置默认操作超时
  opTimeout: 3000